name: Continuous Integration

on: [pull_request]
env:
  NODE_ENV: ${{ secrets.NODE_ENV }}
  PORT: ${{ secrets.PORT }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '13.x'
      - run: touch .env #work around for env-cmd
      - run: yarn install
      - run: yarn test
