name: Eslint & tsc

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: Run eslint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run lint
  tsc:
    runs-on: ubuntu-latest
    name: Check typescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: npm install
      - run: npx tsc
